USE [BD16179]
GO

/****** Object:  Table [BD16179].[tutor]    Script Date: 12/04/2018 08:59:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [BD16179].[tutor](
	[ra] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_tutor] PRIMARY KEY CLUSTERED 
(
	[ra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

